### ISSUE TITLE
TODO:0108

### ISSUE THREAD

**Issue by lizongrui1** [lizongrui1/Issue-tracking#12]
- [x] 学习[Go语言基础之net/http](https://www.liwenzhou.com/posts/Go/http/)以及其他HTTP相关的文章
- [x] 阅读《面向对象》第十一章

**Comment by lizongrui1** [comment]
一个典型的 HTTP 服务应该如图所示：
![20210608210147](https://github.com/lizongrui1/Issue-tracking/assets/82227491/af8f7395-8b84-48ac-b0d0-038ee80b68d6)

**Comment by lizongrui1** [comment]
> http

**Comment by lizongrui1** [comment]
- [ ] [一文说透 Go 语言 HTTP 标准库](https://www.luozhiyun.com/archives/561)
